sudo: required
# services:
#   - docker

before_install:
  - echo "******before******"
  # - docker build -t alexgriff/react-test -f ./client/Dockerfile ./client

scripts:
  - echo "******scripts******"
  # - docker run alexgriff/react-test npm test -- --coverage
# after_success:
#   - docker build -t alexgriff/multi-client -f ./client/Dockerfile.prod ./client
#   - docker build -t alexgriff/multi-server -f ./server/Dockerfile.prod ./server
#   - docker build -t alexgriff/multi-nginx -f ./nginx/Dockerfile.prod ./nginx
#   - docker build -t alexgriff/multi-worker -f ./worker/Dockerfile.prod ./worker
#   # log in to docker cli
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#   # take images and push to docker hub
#   - docker push alexgriff/multi-client
#   - docker push alexgriff/multi-server
#   - docker push alexgriff/multi-nginx
#   - docker push alexgriff/multi-worker
